
2022-04-06 13:19:57,738	INFO services.py:1412 -- View the Ray dashboard at [32m[1mhttp://127.0.0.1:8265
[36m(ServeController pid=24356)[39m 2022-04-06 13:20:02,494	INFO checkpoint_path.py:16 -- Using RayInternalKVStore for controller checkpoint and recovery.
[36m(ServeController pid=24356)[39m 2022-04-06 13:20:02,600	INFO http_state.py:98 -- Starting HTTP proxy with name 'SERVE_CONTROLLER_ACTOR:RRWhok:SERVE_PROXY_ACTOR-node:127.0.0.1-0' on node 'node:127.0.0.1-0' listening on '127.0.0.1:8000'
2022-04-06 13:20:02,869	INFO api.py:521 -- Started Serve instance in namespace 'serve'.
[36m(HTTPProxyActor pid=24354)[39m INFO:     Started server process [24354]
2022-04-06 13:20:02,985	INFO torch_policy.py:162 -- TorchPolicy (worker=local) running on CPU.
2022-04-06 13:20:03,075	INFO ars.py:260 -- Creating shared noise table.
2022-04-06 13:20:15,104	INFO ars.py:265 -- Creating actors.
2022-04-06 13:20:15,125	INFO trainable.py:127 -- Trainable.setup took 12.215 seconds. If your trainable is slow to initialize, consider setting reuse_actors=True to reduce actor creation overheads.
2022-04-06 13:20:15,126	WARNING util.py:55 -- Install gputil for GPU system monitoring.
Traceback (most recent call last):
  File "/Users/liwenyu/Documents/GitHub/RTDM/eva_ray_results.py", line 115, in <module>
    trainer.restore(trained_model)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ray/tune/trainable.py", line 476, in restore
    with open(checkpoint_path + ".tune_metadata", "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/app/data/ray_results/2/ARS_CartPole-v0_661d3_00000_0_2022-03-31_10-07-40/checkpoint_000100/checkpoint-100.tune_metadata'
Traceback (most recent call last):
  File "/Users/liwenyu/Documents/GitHub/RTDM/eva_ray_results.py", line 115, in <module>
    trainer.restore(trained_model)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ray/tune/trainable.py", line 476, in restore
    with open(checkpoint_path + ".tune_metadata", "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/app/data/ray_results/2/ARS_CartPole-v0_661d3_00000_0_2022-03-31_10-07-40/checkpoint_000100/checkpoint-100.tune_metadata'