
2022-04-06 10:45:35,422	INFO services.py:1412 -- View the Ray dashboard at [32m[1mhttp://127.0.0.1:8265
[36m(ServeController pid=21811)[39m 2022-04-06 10:45:38,998	INFO checkpoint_path.py:16 -- Using RayInternalKVStore for controller checkpoint and recovery.
[36m(ServeController pid=21811)[39m 2022-04-06 10:45:39,106	INFO http_state.py:98 -- Starting HTTP proxy with name 'SERVE_CONTROLLER_ACTOR:TMYdkN:SERVE_PROXY_ACTOR-node:127.0.0.1-0' on node 'node:127.0.0.1-0' listening on '127.0.0.1:8000'
2022-04-06 10:45:39,491	INFO api.py:521 -- Started Serve instance in namespace 'serve'.
[36m(HTTPProxyActor pid=21812)[39m INFO:     Started server process [21812]
2022-04-06 10:45:39,555	INFO torch_policy.py:162 -- TorchPolicy (worker=local) running on CPU.
2022-04-06 10:45:39,563	INFO ars.py:260 -- Creating shared noise table.
2022-04-06 10:45:50,245	INFO ars.py:265 -- Creating actors.
2022-04-06 10:45:50,266	INFO trainable.py:127 -- Trainable.setup took 10.733 seconds. If your trainable is slow to initialize, consider setting reuse_actors=True to reduce actor creation overheads.
2022-04-06 10:45:50,269	WARNING util.py:55 -- Install gputil for GPU system monitoring.
[36m(Worker pid=21809)[39m 2022-04-06 10:45:57,149	INFO torch_policy.py:162 -- TorchPolicy (worker=local) running on CPU.
[36m(Worker pid=21809)[39m 2022-04-06 10:45:57,159	WARNING deprecation.py:45 -- DeprecationWarning: `clear_buffer` has been deprecated. Use `Filter.reset_buffer()` instead. This will raise an error in the future!
2022-04-06 10:45:57,360	INFO trainable.py:495 -- Restored on 127.0.0.1 from checkpoint: /Users/liwenyu/Downloads/ray_results/ARS_Hopper-v2_303ed_00000_0_2022-03-30_13-27-47/checkpoint_000100/checkpoint-100
2022-04-06 10:45:57,360	INFO trainable.py:503 -- Current state after restoring: {'_iteration': 100, '_timesteps_total': 2443758, '_time_total': 1292.9797129631042, '_episodes_total': None}
[36m(Worker pid=21810)[39m 2022-04-06 10:45:57,347	INFO torch_policy.py:162 -- TorchPolicy (worker=local) running on CPU.
[36m(Worker pid=21810)[39m 2022-04-06 10:45:57,356	WARNING deprecation.py:45 -- DeprecationWarning: `clear_buffer` has been deprecated. Use `Filter.reset_buffer()` instead. This will raise an error in the future!
difficulty level: 0
difficulty level: 1
difficulty level: 2
difficulty level: 3
difficulty level: 4
difficulty level: 5
difficulty level: 6
difficulty level: 7
difficulty level: 8
difficulty level: 9
difficulty level: 10
difficulty level: 11
difficulty level: 12
difficulty level: 13
difficulty level: 14
difficulty level: 15
difficulty level: 16
difficulty level: 17
difficulty level: 18
difficulty level: 19
[34m[1mwandb[39m[22m: [32m[41mERROR[39m[49m Attempted to change value of key "env_seed" from 1 to 2
[34m[1mwandb[39m[22m: [32m[41mERROR[39m[49m If you really want to do this, pass allow_val_change=True to config.update()
Traceback (most recent call last):
  File "/Users/liwenyu/Documents/GitHub/RTDM/eva_ray_results.py", line 75, in <module>
    wconfig.env_seed = env_seed
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/wandb/sdk/wandb_config.py", line 142, in __setitem__
    key, val = self._sanitize(key, val)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/wandb/sdk/wandb_config.py", line 240, in _sanitize
    raise config_util.ConfigError(
wandb.sdk.lib.config_util.ConfigError: Attempted to change value of key "env_seed" from 1 to 2
If you really want to do this, pass allow_val_change=True to config.update()
Traceback (most recent call last):
  File "/Users/liwenyu/Documents/GitHub/RTDM/eva_ray_results.py", line 75, in <module>
    wconfig.env_seed = env_seed
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/wandb/sdk/wandb_config.py", line 142, in __setitem__
    key, val = self._sanitize(key, val)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/wandb/sdk/wandb_config.py", line 240, in _sanitize
    raise config_util.ConfigError(
wandb.sdk.lib.config_util.ConfigError: Attempted to change value of key "env_seed" from 1 to 2
If you really want to do this, pass allow_val_change=True to config.update()